/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.toutiao.appV2.api.invitation;

import com.toutiao.appV2.model.request.invitation.GetInviteHistoryRequest;
import com.toutiao.appV2.model.request.invitation.InviteHistoryRequest;
import com.toutiao.appV2.model.request.invitation.SuperInviteHistoryRequest;
import com.toutiao.appV2.model.response.invitation.GetInviteHistoryListResponse;
import com.toutiao.appV2.model.response.invitation.GetSuperInviteHistoryResponse;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-11-15T03:28:53.819Z")

@Api(value = "InviteHistoryApi", description = "邀请记录控制器")
public interface InviteHistoryApi {

    @ApiOperation(value = "根据邀请码获取邀请记录列表", nickname = "getInviteHistoryList", notes = "", response = GetInviteHistoryListResponse.class, tags={ "invite-history-controller", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "OK", response = GetInviteHistoryListResponse.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/rest/inviteHistory/getInviteHistoryList",
        produces = { "application/json" },
//        consumes = { "application/json" },
        method = RequestMethod.GET)

    ResponseEntity<GetInviteHistoryListResponse> getInviteHistoryList(GetInviteHistoryRequest getInviteHistoryRequest);


    @ApiOperation(value = "获取三级邀请记录列表", nickname = "getSuperInviteHistory", notes = "",
            response = GetSuperInviteHistoryResponse.class, tags={ "invite-history-controller", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "OK", response = GetSuperInviteHistoryResponse.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/rest/inviteHistory/getSuperInviteHistory",
        produces = { "application/json" },
//        consumes = { "application/json" },
        method = RequestMethod.GET)

    ResponseEntity<GetSuperInviteHistoryResponse> getSuperInviteHistory(SuperInviteHistoryRequest superInviteHistoryRequest);


    @ApiOperation(value = "保存邀请记录", nickname = "saveInviteHistory", notes = "", response = Object.class, tags={
            "invite-history-controller", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "OK", response = Object.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/rest/inviteHistory/saveInviteHistory",
        produces = { "application/json" },
//        consumes = { "application/json" },
        method = RequestMethod.POST)

    ResponseEntity<Object> saveInviteHistory(InviteHistoryRequest inviteHistoryRequest);

}
