/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.toutiao.appV2.api.invitation;

import com.toutiao.appV2.model.request.invitation.GetInviteHistoryRequest;
import com.toutiao.appV2.model.request.invitation.InvitationRequest;
import com.toutiao.appV2.model.response.invitation.GetCodeInfoListResponse;
import com.toutiao.appV2.model.response.invitation.InvitationResponse;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-11-15T03:28:53.819Z")

@Api(value = "InvitationApi", description = "邀请码控制器")
public interface InvitationApi {

    @ApiOperation(value = "根据邀请码获取邀请码信息", nickname = "getCodeInfo", notes = "", response = GetCodeInfoListResponse
            .class, tags={ "invitation-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = GetCodeInfoListResponse.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/rest/invitation/getCodeInfo",
        produces = { "application/json" },
//        consumes = { "application/json" },
        method = RequestMethod.GET)

    ResponseEntity<GetCodeInfoListResponse> getCodeInfo(GetInviteHistoryRequest getInviteHistoryRequest);


    @ApiOperation(value = "主页点击邀请码，获取用户邀请信息以及该设备填写过的邀请记录", nickname = "getInvitation", notes = "",
            response = InvitationResponse.class, tags={ "invitation-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = InvitationResponse.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/rest/invitation/getInvitation",
        produces = { "application/json" },
//        consumes = { "application/json" },
        method = RequestMethod.GET)

    ResponseEntity<InvitationResponse> getInvitation(InvitationRequest invitationRequest);

}
