/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.toutiao.appV2.api.invitation;

import com.toutiao.appV2.model.StringDataResponse;
import com.toutiao.appV2.model.invitation.*;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * @author zym
 */
@Api(value = "邀请码", description = "邀请码接口Api")
public interface InvitationApi {

    @ApiOperation(value = "根据邀请码获取邀请码信息", nickname = "getCodeInfo", notes = "根据邀请码获取邀请码信息",
            response = GetCodeInfoListResponse.class, tags={ "邀请码", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = GetCodeInfoListResponse.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/rest/invitation/getCodeInfo",
        produces = { "application/json" },
//        consumes = { "application/json" },
        method = RequestMethod.GET)

    ResponseEntity<GetCodeInfoListResponse> getCodeInfo(GetInviteHistoryRequest getInviteHistoryRequest);


    @ApiOperation(value = "主页点击邀请码，获取用户邀请信息以及该设备填写过的邀请记录", nickname = "getInvitation",
            notes = "主页点击邀请码", response = InvitationResponse.class, tags={ "邀请码", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = InvitationResponse.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/rest/invitation/getInvitation",
        produces = { "application/json" },
//        consumes = { "application/json" },
        method = RequestMethod.GET)

    ResponseEntity<InvitationResponse> getInvitation(InvitationRequest invitationRequest);

    @ApiOperation(value = "根据邀请码获取邀请记录列表", nickname = "getInviteHistoryList", notes = "根据邀请码获取邀请记录列表",
            response = GetInviteHistoryListResponse.class, tags={ "邀请码", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = GetInviteHistoryListResponse.class),
            @ApiResponse(code = 401, message = "Unauthorized"),
            @ApiResponse(code = 403, message = "Forbidden"),
            @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/rest/invitation/getInviteHistoryList",
            produces = { "application/json" },
//        consumes = { "application/json" },
            method = RequestMethod.GET)

    ResponseEntity<GetInviteHistoryListResponse> getInviteHistoryList(GetInviteHistoryRequest getInviteHistoryRequest);


    @ApiOperation(value = "获取三级邀请记录列表", nickname = "getSuperInviteHistory", notes = "获取三级邀请记录列表",
            response = GetSuperInviteHistoryResponse.class, tags={ "邀请码", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = GetSuperInviteHistoryResponse.class),
            @ApiResponse(code = 401, message = "Unauthorized"),
            @ApiResponse(code = 403, message = "Forbidden"),
            @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/rest/invitation/getSuperInviteHistory",
            produces = { "application/json" },
//        consumes = { "application/json" },
            method = RequestMethod.GET)

    ResponseEntity<GetSuperInviteHistoryResponse> getSuperInviteHistory(SuperInviteHistoryRequest superInviteHistoryRequest);


    @ApiOperation(value = "保存邀请记录", nickname = "saveInviteHistory", notes = "保存邀请记录",
            tags={"邀请码", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = Object.class),
            @ApiResponse(code = 201, message = "Created"),
            @ApiResponse(code = 401, message = "Unauthorized"),
            @ApiResponse(code = 403, message = "Forbidden"),
            @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/rest/invitation/saveInviteHistory",
            produces = { "application/json" },
//        consumes = { "application/json" },
            method = RequestMethod.POST)

    ResponseEntity<StringDataResponse> saveInviteHistory(InviteHistoryRequest inviteHistoryRequest);

}
